// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbRyl3jz5pO8WPvyufvwXLm09rbjD6pcI',
    appId: '1:442530405537:web:45f9541b0a95fad61964e0',
    messagingSenderId: '442530405537',
    projectId: 'obrastudio-75ec9',
    authDomain: 'obrastudio-75ec9.firebaseapp.com',
    storageBucket: 'obrastudio-75ec9.firebasestorage.app',
    measurementId: 'G-78QNBT0TY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP5tt0hr1XSlpyJBnJe-DLu-Rj8V_bAQU',
    appId: '1:442530405537:android:ee268b3ff820b3601964e0',
    messagingSenderId: '442530405537',
    projectId: 'obrastudio-75ec9',
    storageBucket: 'obrastudio-75ec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJyHBUurvQy3kJpOL1jKP6vtZWE0Qy26c',
    appId: '1:442530405537:ios:fcde1de5db9d920e1964e0',
    messagingSenderId: '442530405537',
    projectId: 'obrastudio-75ec9',
    storageBucket: 'obrastudio-75ec9.firebasestorage.app',
    iosBundleId: 'com.example.obraStudio',
  );

}